version: "3.9"

services:

  sonara:

    build:

      context: .

      dockerfile: docker/Dockerfile

    container_name: sonara

    ports:

      - "8000:8000"

      - "7865:7865"

    volumes:

      - ./models:/workspace/models

      - ./outputs:/workspace/outputs

    restart: unless-stopped